#!/bin/bash

active_window=$(hyprctl -j activewindow | jq -r '.title')
hyprctl -j clients | jq -r --arg active "$active_window" '[.[] | select(.workspace.id >= 0) | {title: .title, active: (.title == $active)}] | .[0:10]'