#!/usr/bin/env bash

# Please Use Google Shell Style: https://google.github.io/styleguide/shell.xml

# ---- Start unofficial bash strict mode boilerplate
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o errexit  # always exit on error
set -o errtrace # trap errors in functions as well
set -o pipefail # don't ignore exit codes when piping output
set -o posix    # more strict failures in subshells
# set -x          # enable debugging

IFS=$'\n\t'
# ---- End unofficial bash strict mode boilerplate

cd "$(dirname "${BASH_SOURCE[0]}")"

##### Overlay symlinks into home directory dot files #####
find . -mindepth 2 -type f | sed "s|^\.||" | {
  while IFS= read -r file_path; do
    echo "symlinking ${file_path}"
    directory=$(dirname "${file_path}")
    sudo mkdir -p "${directory}"
    sudo ln -nsf "${PWD}${file_path}" "${file_path}"
  done
}
