#!/usr/bin/env bash

# Please Use Google Shell Style: https://google.github.io/styleguide/shell.xml

# ---- Start unofficial bash strict mode boilerplate
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o errexit  # always exit on error
set -o errtrace # trap errors in functions as well
set -o pipefail # don't ignore exit codes when piping output
set -u          # error on reference to unknown variable
# set -x # enable debugging

IFS=$'\n\t'
# ---- End unofficial bash strict mode boilerplate

cd "$(dirname "${BASH_SOURCE[0]}")"

handle() {
  case $1 in
  workspace*)
    echo "Workspace changed: $1"
    eww update "workspaces=$(./hypr-workspaces)"
    ;;
  activewindow*)
    echo "Window focus changed: $1"
    eww update "clients=$(./hypr-clients)"
    # touch ./eww.yuck
    ;;
  monitoradded*)
    echo "Monitor connected: $1"
    ;;
    # Add more event handlers as needed
  esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
