#!/usr/bin/env bash

# Please Use Google Shell Style: https://google.github.io/styleguide/shell.xml

# ---- Start unofficial bash strict mode boilerplate
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o errexit  # always exit on error
set -o errtrace # trap errors in functions as well
set -o pipefail # don't ignore exit codes when piping output
set -o posix    # more strict failures in subshells
# set -x          # enable debugging

IFS=$'\n\t'
# ---- End unofficial bash strict mode boilerplate

cd "$(dirname "${BASH_SOURCE[0]}")"
# NAME=ergodox \
#   DEVICE='/dev/input/by-id/usb-ErgoDox_EZ_ErgoDox_EZ_0-event-kbd' \
#   envsubst < main.kbd.tpl > "${NAME}.kbd"
# NAME=thinkpad \
#   DEVICE='/dev/input/by-path/platform-i8042-serio-0-event-kbd' \
#   envsubst < main.kbd.tpl > "${NAME}.kbd"

for name in thinkpad macbook ergodox ergodox-infinity-mac; do
  echo -n >"${name}.kbd"
  echo ";; DO NOT EDIT THIS FILE!
;; Edit $0 instead
(defcfg" >>"${name}.kbd"

  case "${name}" in
  thinkpad)
    cat <<EOF >>"${name}.kbd"
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")
  output (uinput-sink "kmonad-${name}")
EOF
    ;;
  ergodox)
    cat <<EOF >>"${name}.kbd"
  input  (device-file "/dev/input/by-id/usb-ErgoDox_EZ_ErgoDox_EZ_0-event-kbd")
  output (uinput-sink "kmonad-${name}")
EOF
    ;;
  macbook)
    cat <<EOF >>"${name}.kbd"
  input (iokit-name "Apple Internal Keyboard / Trackpad")
  output (kext)
EOF
    ;;
  ergodox-infinity-mac)
    cat <<EOF >>"${name}.kbd"
  input (iokit-name "Infinity_Ergodox/QMK")
  output (kext)
EOF
    ;;
  esac

  cat <<EOF >>"${name}.kbd"
  fallthrough true
  allow-cmd false
)

(defsrc
  ;;;;; letters (qwerty)
  - ;; - number row after 0
  = ;; = number row 2nd after 0
  q ;; q
  w ;; w
  e ;; e
  r ;; r
  t ;; t
  y ;; y
  u ;; u
  i ;; i
  o ;; o
  p ;; p
  [ ;; [
  ] ;; ]
  \ ;; \

  a ;; a
  s ;; s
  d ;; d
  f ;; f
  g ;; g
  h ;; h
  j ;; j
  k ;; k
  l ;; l
  ; ;; ;
  ' ;; '

  z ;; z
  x ;; x
  c ;; c
  v ;; v
  b ;; b
  n ;; n
  m ;; m
  , ;; ,
  . ;; .
  / ;; /

  ;;;;; modifiers
  caps ;; caps
  lsft ;; lsft
  rsft ;; rsft
  lctl ;; lctl
  rctl ;; rctl
  lalt ;; lalt
  ralt ;; ralt
  lmet ;; lmet
  ssrq ;; ssrq

  spc ;; spc
)

(defalias
  hyper (around lctl lmet)
  tap-space-hold-shift (tap-hold-next-release 500 spc lsft)
  tap-a-hold-hyper (tap-hold-next-release 500 a @hyper)
  tap-s-hold-hyper (tap-hold-next-release 500 s @hyper)
  tap-escape-hold-control (tap-hold-next-release 200 esc lctl)
  tap-snippet-hold-shift (tap-hold-next-release 100 C-2 lsft)
  tap-fuzzball-hold-super (tap-hold-next-release 200 C-spc lmet)
)

(deflayer dvorak

  ;;;;; letters (dvorak)
  [ ;; - number row after 0
  ] ;; = number row 2nd after 0
  ' ;; q
  , ;; w
  . ;; e
  p ;; r
  y ;; t
  f ;; y
  g ;; u
  c ;; i
  r ;; o
  l ;; p
  / ;; [
  = ;; ]
  \ ;; \

  @tap-a-hold-hyper ;; a
  o ;; s
  e ;; d
  u ;; f
  i ;; g
  d ;; h
  h ;; j
  t ;; k
  n ;; l
  @tap-s-hold-hyper ;; ;
  - ;; '

  ; ;; z
  q ;; x
  j ;; c
  k ;; v
  x ;; b
  b ;; n
  m ;; m
  w ;; ,
  v ;; .
  z ;; /

  ;;;;; modifiers
  @tap-escape-hold-control ;; caps
  @tap-snippet-hold-shift ;; lsft
  @tap-snippet-hold-shift ;; rsft
  _ ;; lctl
  _ ;; rctl
  _ ;; lalt
  _ ;; ralt
  @tap-fuzzball-hold-super ;; lmet
  @tap-fuzzball-hold-super ;; ssrq

  @tap-space-hold-shift ;; spc
)
EOF
done
