gui:
  mouseEvents: false
  theme:
    lightTheme: true
    # activeBorderColor:
    #   - white
    #   - bold
    # inactiveBorderColor:
    #   - white
    selectedLineBgColor:
      # - default
      # - green
      # - "#eee"
      # - underline
      - reverse
      # - '#222222'
    # selectedLineBgColor:
    #   - reverse
    # selectedRangeBgColor:
    #   - reverse
git:
  autoFetch: false
  autoRefresh: false
  # paging:
  #   colorArg: always
  #   pager: /opt/homebrew/bin/delta --dark --paging=never
customCommands:
  - key: 'P'
    context: 'global'
    description: 'Push (quiet)'
    command: "git push -u origin HEAD 2>&1 | grep -viE '(dependabot|vulnerabilities)'"
    output: log
update:
  method: never
