gui:
  mouseEvents: false
  theme:
    lightTheme: false
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      # - reverse
      - '#222222'
    # selectedLineBgColor:
    #   - reverse
    # selectedRangeBgColor:
    #   - reverse
git:
  autoFetch: false
  autoRefresh: false
  # paging:
  #   colorArg: always
  #   pager: /opt/homebrew/bin/delta --dark --paging=never
update:
  method: never
