gui:
  mouseEvents: false
  theme:
    lightTheme: true
    # activeBorderColor:
    #   - white
    #   - bold
    # inactiveBorderColor:
    #   - white
    selectedLineBgColor:
      # - default
      # - green
      # - "#eee"
      # - underline
      - reverse
      # - '#222222'
    # selectedLineBgColor:
    #   - reverse
    # selectedRangeBgColor:
    #   - reverse
git:
  autoFetch: false
  autoRefresh: false
  # paging:
  #   colorArg: always
  #   pager: /opt/homebrew/bin/delta --dark --paging=never
update:
  method: never
