theme = Spring 
copy-on-select = clipboard
# keybind = control+c=copy_to_clipboard
keybind = control+v=paste_from_clipboard
keybind = control+t>s>c=clear_screen
keybind = control+t>w>n=new_window
keybind = control+t>t>n=new_tab
keybind = control+t>c>r=reload_config
keybind = control+t>p=previous_tab
keybind = control+t>n=next_tab
keybind = control+t>1=goto_tab:1
keybind = control+t>2=goto_tab:2
keybind = control+t>3=goto_tab:3
keybind = control+t>4=goto_tab:4
keybind = control+t>5=goto_tab:5
keybind = control+t>6=goto_tab:6
keybind = control+t>7=goto_tab:7
keybind = control+t>8=goto_tab:8
keybind = control+t>9=goto_tab:9
keybind = control+t>t>h=move_tab:-1
keybind = control+t>t>l=move_tab:1
