assume_yes = true
# Run specific steps - same options as the command line flag
only = ["system"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Cleanup temporary or old files
cleanup = true
# Additional git repositories to pull
[git]
repos = [
#    "~/projects/dotfiles",
#    "~/projects/edc",
#    "~/projects/journals"
]

[linux]
arch_package_manager = "yay"
yay_arguments = "--answerclean=None --answerdiff=None --answeredit=None"
# pacman_arguments = "--noconfirm"
