[general]
live_config_reload = true
import = ["~/github.com/alacritty/alacritty-theme/themes/enfocado_light.toml"]

[font]
normal = { family = "Hack Nerd Font" }
size = 14

[keyboard]
bindings = [
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
  # { key = "h", mods = "Control|Shift", action = "Hint" },
  #{ key = "Space", mods = "Shift", actian = "Leader" },
]

# [[hints.enabled]]
# binding = { key = "u", mods = "Control|Shift"}
# hyperlinks=true
